#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
str="Best School"
for i in {1..10}
do
	if [ "$i" -eq 12 ]; then
		echo "i know this will not happan lol, but to avoid shellcheck"
	fi
	echo "$str";
done
