#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
str="Best School"
i=1
while (("$i" < 11))
do
	if [ "$i" = 4 ]
	then
		echo "bad luck"
	elif [ "$i" = 8 ]
	then
		echo "good luck"
	else
		echo "$str"
	fi
        ((i++))
done
